### ISSUE TITLE
Improved logging and displaytext

### ISSUE THREAD

**Issue by solfeggietto** [IKAMR/KDRS_Metadata#1]
Improve logging and displaytext by:
1. Make log window textarea automatic expand and adjust on main window expansion.
2. Add button "Copy log"
3. Add button "Save log" into filename <used filename>.log, if logfile existe save as..._2.log etc.

**Comment by torefa** [comment]
Fixed in v0.7:
1.

**Comment by torefa** [comment]
Fixed in v0.8
