### ISSUE TITLE
Decom JSON import implement checkbox "Include table columns"

### ISSUE THREAD

**Issue by solfeggietto** [IKAMR/KDRS_Metadata#2]
Decom JSON import with unchecked "Include table columns" do include all the tables still (one Excel tab per table).

1. Bug: When unchecked only inlcude the Excel tabs: "DB" and "tables".

2. Bug: Upgrade the DB header section accordingly as for metadata.xml import

Part 1 DB-section:
toolName, toolVersion, systemID, systemVersion, systemInstance, tableCount

Part 2 DB-section:
Keep as is (though move tableCount up to Part 1)
Except replace "SIARD" with "Decom JSON" in cell A10.

Note: on systemID and systemVersion
Part 2 == as is in Decom JSON metadata
Part 1 == empty (to be manually controlled towards the imported Decom JSON template)

**Comment by solfeggietto** [comment]
3. Bug: Also do the same format as import from SIARD metadata.xml.
Excel Tab 1 name = DB
Excel Tab 2 name = tables   (lower case)
Excel Tab 3-n name = 0, 1, 2 etc (corresponding to JSON "table\folder" value and not the "table\name" value"

**Comment by torefa** [comment]
Fixed in v0.7:
1.
2.
3.
