### ISSUE TITLE
Excel tab "tables" bugs in rownames & autofill values

### ISSUE THREAD

**Issue by solfeggietto** [IKAMR/KDRS_Metadata#6]
Excel tab "tables"

1. Bug: metadata.xml rownames order
Correct: row 6 = tablePriority, row 7 = tableEntity, row 8 = tableDescription
Bug now: row 6 = tableDescription, row 7 = tablePriority, row 8 = tableEntity

2. Bug: Decom JSON rownames missing tableEntity
Correct: row 6 = tablePriority, row 7 = tableEntity, row 8 = tableDescription
Bug now: row 6 = tablePriority, row 7 = tableDescription, "tableEntity" not existing

3. Bug: Decom JSON autofill existing "description" and split into "entity" & "description"
Column "entity": if present any [] or {} tags to the left of JSON description
Column "description" All to the right of any [] or {} tages to the left of JSON description
  Any existance of [] or {} in the text after text started must be fullt as is included in description

Excel tab 3-n the individual tables
4. Bug: Implement the "column <<< tables" link in cell A1 for Decom JSON too

5. Bug: Freeze the 4 top rows, just like in imported metadata.xml Excel tab 3-n

6. Bug: description text now ends in column C, but correct is column B
In addition apply to same procedure:
Column "entity": if present any [] or {} tags to the left of JSON description
Column "description" All to the right of any [] or {} tages to the left of JSON description

**Comment by torefa** [comment]
Fixed in v0.7:
1. 
2. 
4. 
5.

**Comment by torefa** [comment]
Fixed in v0.8
6.
